version: "3"
services:
    app:
        build: ./app
        expose:
            - "8000"
        networks:
            - app_network
        volumes:
            - ./app:/code
        hostname: app-server
        restart: always
    web:
        image: nginx
        ports:
            - "80:80"
        networks:
            - app_network
        depends_on:
            - app
        volumes:
            - ./web/project.conf:/etc/nginx/conf.d/default.conf
        restart: always
networks:
        app_network:
            driver: bridge